export const products = [
  {
    name: 'Atakai Set',
    description: 'Atakai Set',
    price: 20,
    rating: 4,
    category: 'sushi',
    onSale: true,
    quantity: 0,
    images: '/uploads/images/atakai set.jpg',
  },
  {
    name: 'Classic Set',
    description: 'Classic Set',
    price: 14.99,
    rating: 4.4,
    category: 'sushi',
    onSale: true,
    quantity: 0,
    images: '/uploads/images/classic set.jpg',
  },
  {
    name: 'Daruma Set',
    description: 'Daruma Set',
    price: 17.49,
    rating: 4.7,
    category: 'sushi',
    onSale: true,
    quantity: 0,
    images: '/uploads/images/daruma set.jpg',
  },
  {
    name: 'Double Hit',
    description: 'Double Hit',
    price: 23.99,
    rating: 4.8,
    category: 'sushi',
    onSale: true,
    quantity: 0,
    images: '/uploads/images/double hit.jpg',
  },
  {
    name: 'Filabum Set',
    description: 'Filabum Set',
    price: 20.0,
    rating: 4.1,
    category: 'sushi',
    onSale: false,
    quantity: 0,
    images: '/uploads/images/filabum set.jpg',
  },
  {
    name: 'Filakalifa Set',
    description: 'Filakalifa Set',
    price: 22.49,
    rating: 4.9,
    category: 'sushi',
    onSale: true,
    quantity: 0,
    images: '/uploads/images/filakalifa set.jpg',
  },
  {
    name: 'Fune Set',
    description: 'Fune Set',
    price: 17.89,
    rating: 4.6,
    category: 'sushi',
    onSale: true,
    quantity: 0,
    images: '/uploads/images/fune set.jpg',
  },
  {
    name: 'Gourme Set',
    description: 'Gourme Set',
    price: 19.89,
    rating: 4.7,
    category: 'sushi',
    onSale: true,
    quantity: 0,
    images: '/uploads/images/gourme set.jpg',
  },
  {
    name: 'Haru Set',
    description: 'Haru Set',
    price: 14.89,
    rating: 4.8,
    category: 'sushi',
    onSale: true,
    quantity: 0,
    images: '/uploads/images/haru set.jpg',
  },
  {
    name: 'Imperator Set',
    description: 'Imperator Set',
    price: 27.49,
    rating: 4.7,
    category: 'sushi',
    onSale: true,
    quantity: 0,
    images: '/uploads/images/imperator set.jpg',
  },
  {
    name: 'Kalifornia Grill Set',
    description: 'Kalifornia Grill Set',
    price: 17.99,
    rating: 4.4,
    category: 'sushi',
    onSale: true,
    quantity: 0,
    images: '/uploads/images/kalifornia grill set.jpg',
  },
  {
    name: 'Kosta Set',
    description: 'Kosta Set',
    price: 16.99,
    rating: 4.7,
    category: 'sushi',
    onSale: true,
    quantity: 0,
    images: '/uploads/images/kosta set.jpg',
  },
  {
    name: 'Laki Set',
    description: 'Laki Set',
    price: 13.0,
    rating: 4.8,
    category: 'sushi',
    onSale: true,
    quantity: 0,
    images: '/uploads/images/laki set.jpeg',
  },
  {
    name: 'New Set',
    description: 'New Set',
    price: 16.0,
    rating: 4.9,
    category: 'sushi',
    onSale: true,
    quantity: 0,
    images: '/uploads/images/new set.jpg',
  },
  {
    name: 'Student Set',
    description: 'Student Set',
    price: 11.0,
    rating: 4.8,
    category: 'sushi',
    onSale: true,
    quantity: 0,
    images: '/uploads/images/student set.jpg',
  },
  {
    name: 'Take Set',
    description: 'Take Set',
    price: 18.99,
    rating: 4.8,
    category: 'sushi',
    onSale: true,
    quantity: 0,
    images: '/uploads/images/take set.jpg',
  },
  {
    name: 'Tanoshimi Set',
    description: 'Tanoshimi Set',
    price: 17.49,
    rating: 5.0,
    category: 'sushi',
    onSale: true,
    quantity: 0,
    images: '/uploads/images/tanoshimi set.jpg',
  },
  {
    name: 'Tokio Set',
    description: 'Tokio Set',
    price: 19.0,
    rating: 4.9,
    category: 'sushi',
    onSale: true,
    quantity: 0,
    images: '/uploads/images/tokio set.jpg',
  },
];
